name: Beautiful Jekyll CI
on: [push, pull_request]
jobs:
  build:
    name: Build Jekyll
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7' # or another compatible Ruby version
      - name: Install dependencies
        run: |
          gem update --system 3.3.22 # Ensure RubyGems is up to date
          bundle install
      - name: Build the site
        run: bundle exec jekyll build --future
